### PR TITLE
Adding OSGi metadata to existing projects without changing the packag…

### PR DESCRIPTION
**Pull request by johnou**
…ing type.

### CODE REVIEW

**Comment by johnou** [comment]
@bertramn PTAL.

**Comment by bertramn** [comment]
Looks good, dropped it into Karaf 4 and budnle comes up nicely. The only optimisation would be to consider if any of the packages can be considered "internal" use and excluded from export. But by the looks of it there is at least 1 class one would typically use in each package (not that this matters much TBH).

**Comment by johnou** [comment]
@lukehutch I think we are good to go :)

**Comment by lukehutch** [comment]
Thanks, @johnou . @bertramn , you could exclude the utils subpackage if you would like, those classes are all for internal use. I suspect you don't feel too strongly about this based on your comment "not that this matters much TBH", so I'll merge this PR now -- feel free to submit another one if you want to exclude utils from export.

**Comment by lukehutch** [comment]
Released in version 2.0.4.

**Pull request merged**
