### PR TITLE
auto-activate release profile when doing release

### PR DESCRIPTION
**Pull request by jjYBdx4IL**
That's what I do in my own projects.

### CODE REVIEW

**Comment by jjYBdx4IL** [comment]
ie.

     		<profile>
      			<id>release</id>
     +			<activation>
     +				<property>
     +					<name>performRelease</name>
     +					<value>true</value>
     +				</property>
     +			</activation>

**Comment by jjYBdx4IL** [comment]
but yeah, you should probably also use the hint you pointed out, ie. tell the release plugin which profile to use. Can't say for sure because I can't test that stuff here.

**Comment by lukehutch** [comment]
Thanks for this..

**Comment by lukehutch** [comment]
@jjYBdx4IL It looks like this fixed it -- released as 2.2.1, and it made it to Sonatype this time.

**Comment by jjYBdx4IL** [comment]
Cool.

**Pull request merged**
