### PR TITLE
Issue #130 Add more classloaders for Traditional Websphere

### PR DESCRIPTION
**Pull request by RaimondKempees**
Unsure whether we should add @sbespalov, could you give your thoughts? The consequence is that scanning will obviously take longer. Also - the ProtectionClassLoader is there for a reason: we might want to prevent access to it?

Further - I updated this fork by rebasing. Not sure if you want to merge like it is or cimply cherry pick my commit.

### CODE REVIEW

**Comment by lukehutch** [comment]
@RaimondKempees It looks like you based this on 2.4.1, can you please re-base on master? Thanks.

**Comment by lukehutch** [comment]
@RaimondKempees I just cherry-picked the change. Thanks!

**Comment by RaimondKempees** [comment]
Hey Luke,

Shame on me. Think I made a boolean logic error:

if (!"com.ibm.ws.classloader.CompoundClassLoader".equals(c.getName())
        || !"com.ibm.ws.classloader.ProtectionClassLoader".equals(c.getName())
        || !"com.ibm.ws.bootstrap.ExtClassLoader".equals(c.getName())) {
    continue;
}

The ORs should be ANDs!

Could this be fixed asap please? Should be possible to overwrite 2.4.6
in Maven Central..

Sorry!

Rai

**Comment by lukehutch** [comment]
Shame on me too for not noticing! I will fix this now.. But I have never
had luck with changing anything in Maven Central. I think it is designed
for write-once.

**Pull request closed without merging**
