### PR TITLE
Support Java 7

### PR DESCRIPTION
**Pull request by danhaywood**
I'd like to use your project (great work by the way) in Apache Isis, and remove our dependency on Reflections and (from some spiking I've done) reduce our start-up times.

Unfortunately in Apache Isis we are still committed to supporting Java 7, whereas you are building the project for Java 8-only.  

I decided to fork the project to see if it could be backported, and seemingly it can with only a couple of changes to test files.  Other changes in this PR are just some configuration to maven-javadoc-plug (to suppress errors thrown up by docLink) and update ..gitignore to ignore IntelliJ project files.

I expect we'll move Isis up to Java 8 within the next 12 months (certainly not beyond the release of Java 9 in Sept 2016) so perhaps you'd consider supporting Java 7 until then?

ALTERNATIVELY, perhaps you'd be happy to just push this branch out to Maven central as a one-off, eg with a version "1.4.1.jdk7" or similar?

### CODE REVIEW

**Comment by lukehutch** [comment]
Hi Dan, I'm glad it works for you, I appreciate the patch, and I agree, some of these Reflections-type libraries are massive overkill for many projects, and can incur a big speed penalty!

I intended to not use Java 8 features in FastClasspathScanner itself once I realized it carries an overhead of 30-40ms the first time you use a lambda or similar feature. The test code definitely doesn't need to be based on Java 8, so I'm happy to drop down the minimum version requirement.

I just pushed out version 1.6.0 to Maven with your patches incorporated. Please test and let me know.

Feel free to mention the benefits of FastClasspathScanner on the Apache Isis site if you'd like :-)

**Comment by danhaywood** [comment]
Thanks for turning this round so quickly, Luke.

I've added a note thanking you to our "thanks" page [1]

Cheers
Dan

[1] http://isis.apache.org/more-thanks.html

**Comment by lukehutch** [comment]
You're welcome, Thanks again for the patch! BTW, not a big deal, but my
name is Luke Hutchison, not Luke Hutch :)

**Comment by danhaywood** [comment]
Apols; name fixed!

cheers
Dan

**Comment by lukehutch** [comment]
Hi Dan, just a quick question on your request to drop the Java dependency from Java 8 to Java 7. I have several classes marked with the FunctionalInterface annotation; was this a problem for you when running under Java 7? Did you just remove these annotations in your own local copy, or were you using JDK 8 in Java 7 compatibility mode?

**Comment by danhaywood** [comment]
The latter... I compiled with JDK 1.8 but with the maven-compile-plugin
configured with target (and, IIRC, source) set to 1.7.

**Pull request merged**
